@authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M2ZGZmMGE4Y2YyNDNiYzM5ZDYwN2UiLCJpYXQiOjE3NDEwODc3NjAsImV4cCI6MTc0MTA5NDk2MH0.i74lRLiHwM7tWRlZY890o1OVhS4E0nU5ZPUQUOj1rNQ    
    
POST http://localhost:3000/api/tracks HTTP/1.1
Content-Type: application/json

{
    "name": "Pruebadatofake",
    "album": "album",
    "cover": "http://tttt.com",
    "dta": "fake",
    "artist": {
        "name": "Ric",
        "nickname": "username",
        "nationality": "ESP"
    }, 
    "duration": {
        "start": 1, 
        "end": 2
    },
    "mediaId": "60d5f9a2f7b6c914d8a9e3b0",
    "config": {
        "timestamp": true, 
        "versionKey": false
    }
}
###

###

GET http://localhost:3000/api/tracks HTTP/1.1
Content-Type: application/json


###
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "Prueba",
  "age": 30,
  "email": "correo_unico@example.com",
  "password": "pass1234",
  "role": "admin"
}


###
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "hola",
  "age": 30,
  "email": "hola@example.com",
  "password": "1234asdf",
  "role": "user",
  "config": {
    "timestamp": true, 
    "versionKey": false
  }
}


###
GET http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:3000/api/users/67add34478030fc629ed9d84

###
GET http://localhost:3000/api/tracks/67add026a44a2269cbb14769 HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/api/tracks HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/api/storage HTTP/1.1
Content-Type: multipart/form-data; boundary=boundry

--boundry
Content-Disposition: form-data; name="image"; filename="image.jpg"
Content-Type: image/jpg

< ./image.jpg
--boundry--

###
DELETE http://localhost:3000/api/tracks/67add026a44a2269cbb14769

###
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Juan Pérezaaa",
  "age": 40,
  "email": "juan.perez.prueba@example.com",
  "password": "pass1234"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "age": 25,
  "email": "test@example.com",
  "password": "pass1234"
}


###
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
 "email": "test@example.com",
 "password": "pass1234"
}


###
GET http://localhost:3000/api/tracks
Authorization: {{authToken}}