@authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U1MjUzZTc2NWQwZTljMGY3NGEwZmEiLCJpYXQiOjE3NDMwNzA1MjYsImV4cCI6MTc0MzA3NzcyNn0.LjpeZCkA6sEc-tWYDZ55Wc-V97mBEgwVDOaxc9bm7aA

### Registro de usuario
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Usuario eliminar",
  "age": 20,
  "email": "usuarioeliminar@example.com",
  "password": "pass1234"
}


### Registro de usuario autónomo
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Guillermo autonomo",
  "age": 20,
  "email": "guillermo@gmail.com",
  "password": "pass1234"
}


### Login de usuario
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "usuarioeliminar@example.com",
  "password": "pass1234"
}

### Validación de email
PUT http://localhost:3000/api/auth/validate HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
  "code": "515612"
}

### Onboarding (actualizar datos personales)
PUT http://localhost:3000/api/users/onboarding
Authorization: {{authToken}}
Content-Type: application/json

{
  "name": "Cambio",
  "lastname": "Casaus",
  "nif": "12345678A",
}

### Actualizar datos de la empresa
PATCH http://localhost:3000/api/users/company
Authorization: {{authToken}}
Content-Type: application/json

{
  "companyName": "MiEmpresa",
  "cif": "B12345678",
  "address": "Calle Falsa 123"
}

### Subir logo a IPFS y guardar en BD
POST http://localhost:3000/api/storage
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="logo"; filename="logo.jpg"
Content-Type: image/jpeg

< ../logo.jpg
--boundary--


### Obtener usuario a partir del token JWT
GET http://localhost:3000/api/users/me
Authorization: {{authToken}}

### DELETE usuario (hard delete)
DELETE http://localhost:3000/api/users/me?soft=false
Authorization: {{authToken}}
Content-Type: application/json

### Solicitar recuperación de contraseña
POST http://localhost:3000/api/auth/recover-password
Content-Type: application/json

{
  "email": "usuarioeliminar@example.com"
}

### Verificar token de recuperación
GET http://localhost:3000/api/auth/recover-password/verify?token=90cce6665cdde3c52acf347487ed41b154ddcb86


### Cambiar contraseña con el token
POST http://localhost:3000/api/auth/recover-password/reset
Content-Type: application/json

{
  "token": "90cce6665cdde3c52acf347487ed41b154ddcb86",
  "newPassword": "nuevaPassword123"
}



